In [269]:
import numpy as np

#INPUTS: Array of beta values with expression of Id4, Huwe1 respectively
#OUTPUTS: Modified array of gene expressions + quiescense state
def quiescense(Genearray, lesser_weight, pos_bias):
    #Independant variables: Id4, Huwe1. Huwe1 effect dilluted by factor of 10
    beta_Id4=Genearray[0]
    beta_Huwe1=Genearray[1] * lesser_weight
    #Calculates non_Inputted gene expressions E47 and Ascl1, and quiescence state
    beta_E47 = pos_bias - beta_Id4
    beta_Ascl1 = beta_E47 *beta_Huwe1
    #Returns sample array with decisions made according to circuit
    Modified_Genearray = []
    Modified_Genearray.extend([beta_Id4, beta_Huwe1, beta_E47, beta_Ascl1])
    return Modified_Genearray

In [303]:
#Demo array input, output array

quiescense(Genearray=np.random.rand(2,10), pos_bias=1, lesser_weight=0.1)

[array([0.4759809 , 0.51176684, 0.5169432 , 0.13791847, 0.81205507,
        0.75933883, 0.84894254, 0.62004546, 0.18593887, 0.94180594]),
 array([0.07338162, 0.04507785, 0.01715552, 0.00721893, 0.08609145,
        0.05691923, 0.04351011, 0.02595893, 0.08541346, 0.05748583]),
 array([0.5240191 , 0.48823316, 0.4830568 , 0.86208153, 0.18794493,
        0.24066117, 0.15105746, 0.37995454, 0.81406113, 0.05819406]),
 array([0.03845337, 0.0220085 , 0.00828709, 0.00622331, 0.01618045,
        0.01369825, 0.00657253, 0.00986321, 0.06953178, 0.00334533])]